service: ai-demo-api

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  esbuild:
    bundle: true
    minify: false

provider:
  name: aws
  runtime: nodejs20.x
  stage: prod
  region: us-west-2 # us-west-2 = Oregon
  environment: ${file(env.yml):${self:provider.stage}}
  tags:
    client: ks-machine-learning

functions:
  createAutoMLJob:
    handler: functions/createAutoMLJob.main
  createEndpoint:
    handler: functions/createEndpoint.main
  createModel: 
    handler: functions/createModel.main
  describeAutoMLJob:
    handler: functions/describeAutoMLJob.main
  describeEndpoint:
    handler: functions/describeEndpoint.main
  uploadFile:
    handler: functions/uploadFile.main
  
